'use strict';
const $=id=>document.getElementById(id);
const mirrors=['https://de1.api.radio-browser.info','https://nl1.api.radio-browser.info','https://at1.api.radio-browser.info'];
let stations=[],current=null,favMode=false,requestId=0,offset=0,hls=null,playId=0,playTimer;
let favourites=[];
try{const saved=JSON.parse(localStorage.getItem('literadio-favourites')||'[]');if(Array.isArray(saved))favourites=saved.filter(s=>s&&typeof s.stationuuid==='string'&&typeof s.name==='string');}catch{}
const audio=$('audio');audio.volume=.75;
let map,markers;
if(window.L){map=L.map('map').setView([12,0],2);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>',maxZoom:18}).addTo(map);markers=L.layerGroup().addTo(map);}else $('map').textContent='Map unavailable. You can still search and play stations.';
async function api(path){for(const host of mirrors){try{const res=await fetch(host+'/json/'+path,{signal:AbortSignal.timeout(10000)});if(!res.ok)throw Error('API unavailable');return await res.json();}catch{}}throw Error('Unable to reach the station directory. Check your connection and try Search again.');}
function safeURL(value){try{const u=new URL(value);return u.protocol==='https:'?u.href:null;}catch{return null;}}
function isSaved(s){return favourites.some(f=>f.stationuuid===s.stationuuid);}
function save(s){favourites=isSaved(s)?favourites.filter(f=>f.stationuuid!==s.stationuuid):[...favourites,s];try{localStorage.setItem('literadio-favourites',JSON.stringify(favourites));}catch{$('status').textContent='Favourites work for this visit; browser storage is unavailable.';}render();}
function render(){const list=$('stations');list.replaceChildren();markers?.clearLayers();const visible=favMode?favourites.filter(s=>(!$('search').value||s.name.toLowerCase().includes($('search').value.toLowerCase()))&&(!$('country').value||s.countrycode===$('country').value)&&(!$('genre').value||(s.tags||'').includes($('genre').value))):stations;
$('list-title').textContent=favMode?'Your favourites':'Explore stations';
for(const s of visible){const row=document.createElement('div');row.className='station'+(current?.stationuuid===s.stationuuid?' active':'');const play=document.createElement('button');play.className='play';play.textContent='▶';play.setAttribute('aria-label','Play '+s.name);play.onclick=()=>playStation(s);const info=document.createElement('div');info.className='station-info';const name=document.createElement('strong');name.textContent=s.name;const detail=document.createElement('small');detail.textContent=[s.country,s.state,(s.tags||'').split(',').slice(0,2).join(' · ')].filter(Boolean).join(' · ');info.append(name,detail);const star=document.createElement('button');star.className='save';star.textContent=isSaved(s)?'♥':'♡';star.setAttribute('aria-label',(isSaved(s)?'Remove favourite ':'Save favourite ')+s.name);star.setAttribute('aria-pressed',String(isSaved(s)));star.onclick=()=>save(s);row.append(play,info,star);list.append(row);
if(map&&Number.isFinite(s.geo_lat)&&Number.isFinite(s.geo_long)){const popup=document.createElement('div');const title=document.createElement('strong');title.textContent=s.name;const button=document.createElement('button');button.textContent='Listen';button.style.marginLeft='10px';button.onclick=()=>playStation(s);popup.append(title,button);L.circleMarker([s.geo_lat,s.geo_long],{radius:6,color:'#284522',fillColor:'#a2e961',fillOpacity:.9,weight:1}).bindPopup(popup).addTo(markers);}}
if(favMode)$('status').textContent=visible.length?visible.length+' saved stations':'No favourites found. Save stations using the heart button.';
$('more').hidden=favMode||stations.length<offset+100;
}
async function load(append=false){const id=++requestId;if(favMode){render();return;}if(!append)offset=0;else offset+=100;$('status').textContent='Finding live stations…';$('more').disabled=true;const query=new URLSearchParams({hidebroken:'true',is_https:'true',order:'votes',reverse:'true',limit:'100',offset:String(offset)});if($('search').value.trim())query.set('name',$('search').value.trim());if($('country').value)query.set('countrycode',$('country').value);if($('genre').value)query.set('tag',$('genre').value);
try{const result=await api('stations/search?'+query);if(id!==requestId)return;stations=append?[...stations,...result]:result;$('status').textContent=stations.length?stations.length+' stations · choose one to listen':'No stations found. Try another name, country or genre.';render();if(!append&&map){const located=stations.filter(s=>Number.isFinite(s.geo_lat)&&Number.isFinite(s.geo_long));if(located.length)map.fitBounds(located.map(s=>[s.geo_lat,s.geo_long]),{padding:[30,30],maxZoom:7});}}catch(e){if(id===requestId){$('status').textContent=e.message;if(append)offset-=100;}}finally{if(id===requestId)$('more').disabled=false;}}
function audioStatus(text){$('audio-status').textContent=text;}
async function playStation(s){const id=++playId;clearTimeout(playTimer);hls?.destroy();hls=null;audio.pause();audio.removeAttribute('src');audio.load();current=s;$('playing-name').textContent=s.name;$('playing-detail').textContent=[s.country,s.language,s.bitrate?s.bitrate+' kbps':''].filter(Boolean).join(' · ');$('toggle').disabled=false;render();audioStatus('Connecting…');const url=safeURL(s.url_resolved||s.url);if(!url){audioStatus('This station has no secure stream. Try another.');return;}if(map&&Number.isFinite(s.geo_lat)&&Number.isFinite(s.geo_long))map.flyTo([s.geo_lat,s.geo_long],Math.max(map.getZoom(),5));
api('url/'+encodeURIComponent(s.stationuuid)).catch(()=>{});
playTimer=setTimeout(()=>{if(id===playId&&audio.paused)audioStatus('Connection is taking too long. Try another station.');},15000);
try{if((s.hls===1||/\.m3u8(?:\?|$)/i.test(url))&&!audio.canPlayType('application/vnd.apple.mpegurl')){if(!window.Hls?.isSupported())throw Error('This browser cannot play this station format.');hls=new Hls();hls.loadSource(url);hls.attachMedia(audio);hls.on(Hls.Events.MANIFEST_PARSED,()=>{if(id===playId)audio.play().catch(()=>audioStatus('Press Play to start listening.'));});hls.on(Hls.Events.ERROR,(_,data)=>{if(data.fatal&&id===playId){audioStatus('Stream unavailable. Try another station.');hls?.destroy();hls=null;}});}else{audio.src=url;await audio.play();}}catch(e){if(id===playId)audioStatus(e.name==='NotAllowedError'?'Press Play to start listening.':'Stream unavailable or unsupported. Try another station.');}
if('mediaSession' in navigator){navigator.mediaSession.metadata=new MediaMetadata({title:s.name,artist:s.country||'Live radio',album:'LiteRadio'});}}
audio.addEventListener('playing',()=>{clearTimeout(playTimer);audioStatus('Live · listening');$('toggle').textContent='❚❚';$('toggle').setAttribute('aria-label','Pause radio');});audio.addEventListener('pause',()=>{$('toggle').textContent='▶';$('toggle').setAttribute('aria-label','Play radio');if(current)audioStatus('Paused');});audio.addEventListener('waiting',()=>audioStatus('Buffering…'));audio.addEventListener('error',()=>{clearTimeout(playTimer);if(current)audioStatus('Stream unavailable or region-restricted. Try another station.');});
$('toggle').onclick=()=>{if(audio.paused)audio.play().catch(()=>audioStatus('Unable to play. Choose another station.'));else audio.pause();};$('volume').oninput=e=>audio.volume=Number(e.target.value);
$('search-form').onsubmit=e=>{e.preventDefault();load();};$('country').onchange=()=>load();$('genre').onchange=()=>load();$('more').onclick=()=>load(true);$('favourites').onclick=()=>{favMode=!favMode;++requestId;$('favourites').setAttribute('aria-pressed',String(favMode));$('favourites').textContent=favMode?'← Explore':'♡ Favourites';load();};$('reset').onclick=()=>{$('search').value='';$('country').value='';$('genre').value='';load();};
if('mediaSession' in navigator){navigator.mediaSession.setActionHandler('play',()=>audio.play().catch(()=>{}));navigator.mediaSession.setActionHandler('pause',()=>audio.pause());}
api('countries?hidebroken=true').then(countries=>{const selected=$('country').value;$('country').replaceChildren(new Option('All countries',''));countries.sort((a,b)=>a.name.localeCompare(b.name)).forEach(c=>{if(c.iso_3166_1)$('country').add(new Option(c.name,c.iso_3166_1));});$('country').value=selected;}).catch(()=>{});
load();
